"""Ports for team / player persistence."""

from __future__ import annotations

from typing import Protocol

from app.domain.tournament.team_entities import Player, Team


class TeamRepository(Protocol):
    def add(self, team: Team) -> None: ...

    def get(self, team_id: str) -> Team | None: ...

    def save(self, team: Team) -> None: ...

    def delete(self, team_id: str) -> None: ...

    def list_for_tournament(self, tournament_id: str) -> list[Team]: ...

    def find_by_name(self, tournament_id: str, name: str) -> Team | None: ...

    def count_for_tournament(self, tournament_id: str) -> int: ...


class PlayerRepository(Protocol):
    def add(self, player: Player) -> None: ...

    def get(self, player_id: str) -> Player | None: ...

    def save(self, player: Player) -> None: ...

    def delete(self, player_id: str) -> None: ...

    def list_for_team(self, team_id: str) -> list[Player]: ...

    def delete_for_team(self, team_id: str) -> None: ...

    def count_for_team(self, team_id: str) -> int: ...
